### ISSUE TITLE
Replacing Emoji won't work on Linux with Slack App 3.2.0

### ISSUE THREAD

**Issue by micxxx** [IvyBits/old-slack-emojis#5]
Hi,

I would like to report that replacing Emoji using your shell script no longer works on Linux with Slack App 3.3.0-beta2 HEAD/517150e 64-bit (Cartoon Heroes). The script reports it has successfully installed the emojis, but it does not.

![slack_emoji_bug](https://user-images.githubusercontent.com/3817976/40544912-1dcb2b4a-602a-11e8-88bd-66693ee20e31.png)

OS: Ubuntu Ubuntu 17.10 64-bit
Slack: 3.3.0-beta2 HEAD/517150e 64-bit (Cartoon Heroes)

**Comment by focs** [comment]
I can confirm that it doesn't work on `linux 3.2.1 64-bit`

**Comment by quantum5** [comment]
This should be fixed in 456264166a8196bd9e7c17225d44b01c9a39711a.

**Comment by focs** [comment]
fixed!
